### ISSUE TITLE
Printing the Parts

### ISSUE THREAD

**Issue by Tim-Gabrikowski** [poboisvert/GPTARS_Interstellar#1]
Hello,

I am planning on building a GPTARS for myself and I was wondering, If all the parts could be printed using PLA, or if any parts need to be stronger and therefore need to be printed using steel/aluminium. I would probably say, if the whole casing is made of PLA, It would not be as heavy so it could handle it?

BTW: When I am really building it, I would like to contribute to this repo and provide more information I collect while building or programming...

**Comment by poboisvert** [comment]
I am cleaning up the .step files right now. The case shall be in PLA/ABS. Arms (the red in metal if possible) except to the case holder. Feel free to push information. I am waiting for the motors right now... Be sure to not print the motor and motor brackets

**Comment by Tim-Gabrikowski** [comment]
Could you export all the different parts as .stl files and name them in some way? So that Anyone can clearly see which part is which and needs to be printed with which material? Thanks!
